language: php
php:
- '7.0'
services:
- docker

# Install lando
before_install:
  - sudo apt-get -y update || true
  - sudo apt-get -y install cgroup-bin curl
  - curl -fsSL -o /tmp/lando-latest.deb http://installer.kalabox.io/lando-latest-dev.deb
  - sudo dpkg -i /tmp/lando-latest.deb
  - lando version

# Do the lando magic
script:

  # Get our built out lando site running on travis
  - lando start -- -v
  - lando composer install
  # Do needed things to get this repo transformed to what pantheon expects
  # - lando composer prepare-for-pantheon

  # Run non-db required tests eg linting/code standards/unit tests
  # Lint the codez
  - lando phplint
  - lando blt deploy

  # Check code standards
  # - lando phpcs --config-set installed_paths /app/vendor/drupal/coder/coder_sniffer
  # - lando phpcs -n --report=full --standard=Drupal --ignore=*.tpl.php --extensions=install,module,php,inc web/modules web/themes web/profiles

  # Run unit tests.
  # - lando composer drupal-unit-tests

addons:
  ssh_known_hosts: svn-6182.devcloud.hosting.acquia.com
  chrome: stable

deploy:
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: develop
       php: 7.2
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: master
       php: 7.2
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_tag"
     skip_cleanup: true
     on:
       tags: true
       php: 7.2
